version: '3.8'
services:
  postgres:
    image: postgres:14
    container_name: airline-coverage-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: airline_coverage
    ports:
      - '5434:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - airline_coverage_network

  adminer:
    image: adminer
    container_name: adminer
    environment:
      ADMINER_DEFAULT_SERVER: postgres
    ports:
      - '8080:8080'
    networks:
      - airline_coverage_network

networks:
  airline_coverage_network:
    driver: bridge

volumes:
  postgres_data:
